# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!name: "PKUAutoSubmit"

description: "燕园云战役自动填报小助手"

inputs:
  username:
    description: "IAAA 用户名"
    required: true
  password:
    description: "IAAA 密码"
    required: true
  campus:
    description: "所在校区 (燕园、万柳、畅春园、圆明园、中关新园)"
    required: true
    default: "燕园"
  reason:
    description: "出入校事由"
    required: true
    default: "恰饭"
  in_habitation:
    description: "入校前居住地 (北京、京外)"
    required: true
    default: "北京"
  in_district:
    description: "居住地所在区"
    required: true
    default: "海淀区"
  in_street:
    description: "居住地所在街道"
    required: true
    default: "燕园街道"
  out_destination:
    description: "出校目的地 (北京、京外)"
    required: true
    default: "北京"
  out_track:
    description: "出校行动轨迹"
    required: true
    default: "燕园-畅春园"
  wechat:
    description: "是否需要微信通知 (True / False)"
    required: true
    default: "False"
  sckey:
    description: "方糖 sckey"
    required: true
    default: "xxxxxxxx"

outputs:
  time:
    description: "小助手运行时间"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.campus }}
    - ${{ inputs.reason }}
    - ${{ inputs.in_habitation }}
    - ${{ inputs.in_district }}
    - ${{ inputs.in_street }}
    - ${{ inputs.out_destination }}
    - ${{ inputs.out_track }}
    - ${{ inputs.wechat }}
    - ${{ inputs.sckey }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
